# Automation scripts come from the shared library (seedcx/scraper-mobile-library),
# which is checked out as a submodule at scraper-mobile-library/.
#
# The library commits its built JavaScript, because a customer building this SDK
# through SwiftPM has no Node. So `sync` is a plain copy — nothing is compiled
# here — and the result is committed alongside the submodule pointer in the same
# commit, so the two can never drift apart.
#
# CI re-runs `sync` and fails if anything moves.

LIB     := scraper-mobile-library
SCRIPTS := Sources/ZerohashSDK/AutomationScripts

# The header the library stamps on everything it builds. `sync` deletes on this,
# so it has to match tools/build.mjs in the library, where a test pins it down.
MARKER  := @generated by scraper-mobile-library

.PHONY: sync bump check-sync

## Copy the library's built scripts into the SDK.
##
## Removes before copying, so a script the library STOPS producing cannot survive
## here. Without that, a rename leaves the old file behind and nothing notices:
## sync is a copy, so `git diff` sees an unchanged old file and an
## already-committed new one, and both get shipped.
##
## Only files carrying the library's @generated marker are removed. Scripts that
## have not migrated yet are hand-written, carry no marker, and are left alone.
## The distinction disappears on its own once the last one moves.
sync:
	@test -d $(LIB)/dist || { \
		echo "$(LIB)/dist is missing. Run: git submodule update --init"; exit 1; }
	@grep -l '$(MARKER)' $(SCRIPTS)/*.js 2>/dev/null \
		| while read -r f; do rm -f "$$f"; done
	cp $(LIB)/dist/*.js $(SCRIPTS)/

## Move to a library commit and bring its scripts across in one step.
## Usage: make bump REF=<sha or origin/main>
bump:
	@test -n "$(REF)" || { echo "usage: make bump REF=<sha>"; exit 1; }
	git -C $(LIB) fetch --quiet origin
	git -C $(LIB) checkout --quiet $(REF)
	$(MAKE) --no-print-directory sync
	git add $(LIB) $(SCRIPTS)
	@echo
	@echo "Staged the pointer and the scripts. Commit them together:"
	@echo "  git commit -m \"chore: automation scripts -> $$(git -C $(LIB) rev-parse --short HEAD)\""

## What CI runs: the copy must be a no-op against what is committed.
check-sync: sync
	@git diff --exit-code -- $(SCRIPTS) || { \
		echo; \
		echo "The committed scripts do not match the submodule commit this repo points at."; \
		echo "Run 'make sync' and commit the result in the same commit as the pointer."; \
		exit 1; }
	@echo "scripts match the pinned library commit"
