// Every injected .js has to be declared as a resource in Package.swift.
//
// Nothing enforced this before. A .js added under Sources/ZerohashSDK/ without a
// matching `.process(...)` line compiles fine and fails at runtime: eleven of the
// thirteen loaders in Coinbase.swift call preconditionFailure, which is a crash
// in the CUSTOMER's app rather than an error in our build. The other two —
// setup-execution-context.js and telemetry.js — degrade silently, which is worse
// to diagnose.
//
// It matters more now that AutomationScripts/ is generated by `make sync` from
// the scraper-mobile-library submodule: a script appearing or disappearing there
// is a copy, not a deliberate edit by someone looking at Package.swift.
//
// Lives here rather than in XCTest so it runs in js-tests.yml in seconds without
// a simulator. withdraw-wrapped-script.test.mjs already reads Swift as text, so
// the pattern is established.

import assert from "node:assert/strict";
import { test } from "node:test";
import { readFileSync } from "node:fs";
import { globSync } from "node:fs";
import { fileURLToPath } from "node:url";

const repoRoot = new URL("../../../", import.meta.url);
const manifest = readFileSync(fileURLToPath(new URL("Package.swift", repoRoot)), "utf8");

/** Resource paths declared with .process(...) or .copy(...), relative to the target. */
const declared = new Set(
  [...manifest.matchAll(/\.(?:process|copy)\("([^"]+\.js)"\)/g)].map((m) => m[1]),
);

/** Every .js on disk inside the target, as a target-relative path. */
const onDisk = globSync("Sources/ZerohashSDK/**/*.js", {
  cwd: fileURLToPath(repoRoot),
})
  .map((p) => p.replace(/^Sources\/ZerohashSDK\//, ""))
  .sort();

test("the manifest declares at least one script, so a bad regex cannot pass this file", () => {
  assert.ok(declared.size > 0, "no .js resources parsed out of Package.swift");
  assert.ok(onDisk.length > 0, "no .js found under Sources/ZerohashSDK/");
});

test("every .js in the target is declared in Package.swift", () => {
  const undeclared = onDisk.filter((p) => !declared.has(p));
  assert.deepEqual(
    undeclared,
    [],
    `these scripts would be missing from Bundle.module at runtime, which is a ` +
      `preconditionFailure in a customer's app. Add a .process(...) line for each:\n  ` +
      undeclared.join("\n  "),
  );
});

test("every declared .js exists on disk", () => {
  const missing = [...declared].filter((p) => !onDisk.includes(p)).sort();
  assert.deepEqual(
    missing,
    [],
    `Package.swift declares scripts that are not there. SwiftPM fails the build ` +
      `on a missing resource, so this is caught — but it is caught in a ` +
      `customer's build if it ever ships:\n  ` + missing.join("\n  "),
  );
});

test("the generated directory is declared with its venue prefix intact", () => {
  // The library names its output <folder>-<file>.js, and the mobile side copies
  // that name verbatim. A file under AutomationScripts/ without a prefix means
  // someone renamed a generated file by hand, which `make sync` would silently
  // undo on the next bump.
  const generated = onDisk.filter((p) => p.startsWith("AutomationScripts/"));
  for (const path of generated) {
    assert.match(
      path,
      /^AutomationScripts\/[a-z0-9]+(?:-[a-z0-9]+)*\.js$/,
      `${path} does not look like library output`,
    );
    assert.ok(
      /^AutomationScripts\/(shared|coinbase|kraken)-/.test(path),
      `${path} is missing its venue prefix — generated names carry one`,
    );
  }
});
